version: '3.1'
services:
  dbhiring:
    image: postgres:11
    container_name: hiring-db
    ports:
      - "5433:5432"
    volumes:
      - pg_dbhiring:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hiring
volumes:
  pg_dbhiring:
