version: '3.1'
services:
  apihiring:
    container_name: hiring-api
    image: api:1.0.1
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbhiring
    environment:
      - "SPRING_PROFILES_ACTIVE=stg"
  dbhiring:
    image: postgres:11
    container_name: hiring-db
    ports:
      - "5433:5432"
    volumes:
      - pg_dbhiring:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hiring
volumes:
  pg_dbhiring:
