---
spring:
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          dialect: org.hibernate.dialect.H2Dialect
  ## PostgreSQL
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:hiring
    username: sa
    password: password
    ## default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
server:
  port: 8080

#swagger
springdoc:
  swagger-ui:
    path: swagger-ui
    version:
    title: HIRING
    description: HIRING description
    apiGroupName: hiring
    contact:
      name: HIRING
      email: leo.garay9@gmail.com
    licenseName: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
    api-groups:
      - public
      - private
ApiNobelPrizeMasterData:
  baseUrl: https://api.nobelprize.org/2.0
  nobelPrize: /nobelPrize/{categoria}/{anio}

logging:
  level:
    com:
      zaxxer:
        hikari.HikariConfig: DEBUG
        hikari: TRACE
jwt:
  secret-key: eyJhbGciOiJIUzUxMiJ9
  expiration: 28800000
---
