---

spring:
  datasource:
    url: jdbc:h2:mem:hiring
    username: sa
    password: password

logging:
  level:
    com:
      zaxxer:
        hikari.HikariConfig: DEBUG
        hikari: TRACE

jwt:
  secret-key: eyJhbGciOiJIUzUxMiJ9
  expiration: 28800000