---

spring:
  ## PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5433/hiring
    username: postgres
    password: postgres

logging:
  level:
    com:
      zaxxer:
        hikari.HikariConfig: DEBUG
        hikari: TRACE

jwt:
  secret-key: eyJhbGciOiJIUzUxMiJ9
  expiration: 28800000