---
spring:
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          dialect: org.hibernate.dialect.PostgreSQL81Dialect
  ## PostgreSQL
  datasource:
    ## default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
server:
  port: 8080
---
